### ISSUE TITLE
Sea of Thieves: Support CrossOver 24

### ISSUE THREAD

**Issue by timkurvers** [timkurvers/macos-game-patches#2]
The current patch for CrossOver's credential mechanism only supports CrossOver 23.

CodeWeavers [released CrossOver 24](https://www.codeweavers.com/blog/mjohnson/2024/2/22/crossover-24-with-wine-9-in-record-time) a few days ago.

**Comment by HexArchy** [comment]
I tried to patch myself, but nothing good came out of it. Waiting and hoping for your patch.

**Comment by timkurvers** [comment]
Hope to get this done this week. There seem to be some changes to the CrossOver application that makes this a bit trickier to do than on earlier versions, but should be doable 😊

**Comment by timkurvers** [comment]
Patch for CrossOver 24 available in 03cdcc827ed951f2d0a2d78cde70df63e9f61dae with some docs in d09f4f39b18a15ba83f30dc52d90e77eae07db11.

Unfortunately, even though sign-in works, the game itself is unplayable as D3DMetal seems to crash the game on boot. Performance using DXVK or WineD3D is very poor. Going to keep this issue open until that is resolved 😑

**Comment by Xiaraxe** [comment]
They've just announced that the game will be adding "Easy Anticheat" to its next update, the same one used for Fornite. It doesn't look good for Sea Of Thieves.

**Comment by timkurvers** [comment]
> They've just announced that the game will be adding "Easy Anticheat" to its next update, the same one used for Fornite. It doesn't look good for Sea Of Thieves.

Aiii, I missed that bit. Well, there goes our luck I suppose (for the time being).

**Comment by Xiaraxe** [comment]
Hello, the worst has happened. 
Since the last update it has been impossible to connect to sea of thieves. You get a launch error with the new Easy Anti-Cheat. I don't know if a solution is possible but I hope so.

**Comment by timkurvers** [comment]
Closing this as CX 24 is addressed. Might reopen this once Easy Anti-Cheat support lands, if ever 🙏 (tracked in #4)
