### ISSUE TITLE
Jusant: Patch does not work for build 13334122

### ISSUE THREAD

**Issue by gandreatta99** [timkurvers/macos-game-patches#3]
Hellooo sorry if this is a non-issue but I keep getting the same error when trying to run the patch-jusant.sh file. I've tried both Crossover 24 and 23.7.1 and when I try to patch the ASC-Win64-Shipping.exe I get this error 'Found an unknown version of ASC-Win64-Shipping.exe'. I've tried a few different solutions but none seem to fix it. Is there something glaringly obvious I'm doing wrong? Thanks for making the wonderful fix, hoping I get to try out jusant soon :-)

**Comment by timkurvers** [comment]
Hi! Jusant has probably been updated recently, so the patch will need to be adjusted slightly. Hope to be able to do so today or this weekend at the latest 😊

**Comment by gandreatta99** [comment]
Ur a saint ! Take ur time, thanks so much :,-)

**Comment by timkurvers** [comment]
Have added support for the latest Jusant build in 10412369be1ea2cf72d6828207988cdb5872efc5.

Downloading the patch-file (or pulling in changes from the repo) and then applying the patch once more should work 😊
