### ISSUE TITLE
Sea of Thieves: Easy Anti Cheat

### ISSUE THREAD

**Issue by KohlerVG** [timkurvers/macos-game-patches#4]
Does Sea of Thieves work with Easy Anti Cheat with this patch?

They just released it not too long ago, so I'm curious if it works. This would be amazing if it does.

Would love some comments for people who have it downloaded and tested to see if it works.

**Comment by timkurvers** [comment]
It does not. Unless Easy Anti Cheat comes out with a macOS bridge (similarly to what they've done for Linux/Steam Deck) this will likely remain unplayable.

**Comment by KohlerVG** [comment]
I see that the game run on Proton (SteamDeck) which runs on Wine. Why can't we get it to work in CrossOver then since it also runs on Wine for macOS?

**Comment by timkurvers** [comment]
Easy Anti Cheat for applications running through Wine require a bridge to the host OS. This is available for Proton: https://steamdb.info/app/1826330/info/

This does not exist for macOS / CrossOver, so any EAC enabled game will simply fail with `Unable to load EAC module`. It's likely technically possible to achieve, but the question is whether Epic and/or CodeWeavers deem it worthy of their time.

The best scenario would obviously be a native Sea of Thieves port, with native EAC for macOS.

**Comment by Ashernor** [comment]
I managed to bypass the EasyAntiCheat error by modifying the Settings.json file in the Sea Of Thieves/EasyAntiCheat folder 

If you add a 0 to the product id it works ; just update : 
`"productid" : "0367a3a8ea344f08851d76facf6f66d3",`
to : 
`"productid" : "0367a3a8ea344f08851d76facf6f66d30",`

Though as I can't login as they updated the libcef again I'm not sure it works after that.

**Comment by enzofrnt** [comment]
> I managed to bypass the EasyAntiCheat error by modifying the Settings.json file in the Sea Of Thieves/EasyAntiCheat folder
> 
> If you add a 0 to the product id it works ; just update : `"productid" : "0367a3a8ea344f08851d76facf6f66d3",` to : `"productid" : "0367a3a8ea344f08851d76facf6f66d30",`
> 
> Though as I can't login as they updated the libcef again I'm not sure it works after that.

Working for me.
But no login page.

**Comment by timkurvers** [comment]
Have updated the login screen and CrossOver 24.0.4 patches for the latest build of Sea of Thieves: 019c5bfd65ff6c704100b1a2874f6dc5f6fb1c2a

As Easy Anti-Cheat (correctly) prevents joining the game world (from the main menu) I'll go ahead and close this issue.

Here's to hoping for either an official macOS EAC bridge that can be used with Wine, or a native Sea of Thieves port 🙏
