### ISSUE TITLE
Sea of Thieves on macOS Sequoia

### ISSUE THREAD

**Issue by enzofrnt** [timkurvers/macos-game-patches#7]
With same modification in DLL file as previosly and with modification of anticheat recommanded by the other issue i was able to start the game but i was not able to login. Login page still black, any idea ?
Thanks.

**Comment by enzofrnt** [comment]
I disable also Msync and login page still black.

**Comment by enzofrnt** [comment]
Also, D3DMetal with GPTK2 seems to not be working, game is not loading with it.

**Comment by enzofrnt** [comment]
I don't know what to do.. any help are welcome.

**Comment by timkurvers** [comment]
Have updated the patching script to support the latest Sea of Thieves build: 019c5bfd65ff6c704100b1a2874f6dc5f6fb1c2a

Easy Anti-Cheat will still prevent you from the joining the game world, so use at your own risk.
